### ISSUE TITLE
Simulate an IHC Controler

### ISSUE THREAD

**Issue by zamzon** [dingusdk/arduinoihc#2]
Hi I can see with this a can simulate a in/output module to a IHC controller.

But if I would like to do this the other way around, so use my LK in/output module directly to an MQTT broker, Without the need of an IHC controller.
Do you have something to solve this issue?

**Comment by dingusdk** [comment]
This is  a late answer - (i did not see it and is "cleaning up")

The input and output are  the same - each side of the connectrion. So you can connect an IHC controller output to an input on arduino. And the other way an arduino output to an IHC controler input.  Or you can connect an arduino output to a IHC output module, or an IHC input module to an arduino input.
