### ISSUE TITLE
Connection between IHC controller and Output Module

### ISSUE THREAD

**Issue by jmvaz** [dingusdk/arduinoihc#3]
Hi! First of all thanks for this project!
I have one doubt, how can I assign the pin from the controller to the pin of the arduino/esp8266?
In another words, how can I connect the Arduino/esp8266 to the controller? 

Do you have one example of one output module with 4/8 exits for use with relays?

Kind regards,
Jaime

**Comment by jmvaz** [comment]
@dingusdk can you help me here? thanks

**Comment by dingusdk** [comment]
The data output and input on the IHC controller are standard 5v TTL levels.
If your arduino is 5v you can connect directly (or use a 1K ohm transistor as a safety thing - in case you have an IHC output  and the arduino gpio is also set to output)

If you are using 3.3v on your arduino/ESP you can connect an output from arduino/ESP directly, but to connect an IHC data output to an gpio input you should convert the level. (Use a logic level converter or a simple small signal transistor.) 

If you want the 2 sides to be electrically separated use an optocoupler (Google it , don't ask me to make your project)

If your data is inverted you can change

#define IHC_LOW 0
#define IHC_HIGH 1

in the code.

For making it controll relays - see the examples. BasicInput.ino will print the input - you should be able to change that to control gpio pins - and connect the gpio pins to relays.


And a disclaimer - if you connect something wrong you can probably blow up you arduino/esp or IHC controller. So  if you don't understand what you are doing - don't do it
